### ISSUE TITLE
pyside2-py3.11 osx-arm64 missing

### ISSUE THREAD

**Issue by looooo** [conda-forge/pyside2-feedstock#143]
### Comment:

there is still a build for osx-arm64 py3.11 missing.

**Comment by mbargull** [comment]
I looked at the build error and it's a not terribly obvious case, but here is what happens:
- This recipe is an oddball:
  The cross-compiling build needs its own package (pinned to the minor version) already built for the build platform.
  (I'd guess because it runs some of its own code during the build -- I haven't/will not look into this.)
- New builds for Python <3.11 can just take other builds from previous runs to satisfy their build requirements.
- This first Python 3.11 build needed to take the build platform's build from the current run.
- And here is where it currently blows up (`none of the providers can be installed`):
  - It links to `libclang13`.
  - Previous builds used `libclang13=14.0.4` resulting in a `libclang13>=14.0.4` dependency.
  - The current build used `libclang13=14.0.6` resulting in a `libclang13>=14.0.6` dependency.
  - The used compiler is Clang in version `14.0.4` which pins its `libclang13` to exactly `14.0.4`.
  - `libclang13=14.0.4` together with `libclang13>=14.0.6` is not satisfiable for the build environment.

There are probably multiple (easy) ways to tackle this, but I'll leave the resolution to this to the maintainers/others since I don't know much regarding this package and libclang/LLVM linking to say which is appropriate.

cc @isuruf (added the `pyside2` build req), @chrisburr (dealt with the latest build)

**Comment by mbargull** [comment]
Thanks, Isuru!
I restarted the build and will close this issue once it's up on `conda.anaconda.org`
